"""One-off generator for forward-only busy-index seed JSON (run from repo root).

    python scripts/_gen_busy_forward_seeds.py

Dates were taken from official pages fetched 2026-04-27; re-run after updating
constants below if you extend the forward window.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VER = "2026-04-27"
TODAY = VER  # verification / filter reference date

# --- School holidays: only breaks with start_date >= 2026-04-27 (inclusive) ---

SCHOOL: list[dict] = [
    # NSW Eastern — https://www.education.nsw.gov.au/schooling/calendars/2026
    {
        "state_code": "NSW",
        "year": 2026,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2026-07-06",
        "end_date": "2026-07-17",
        "data_source": "NSW Department of Education",
        "source_url": "https://www.education.nsw.gov.au/schooling/calendars/2026",
        "verified_at": VER,
    },
    {
        "state_code": "NSW",
        "year": 2026,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2026-09-28",
        "end_date": "2026-10-09",
        "data_source": "NSW Department of Education",
        "source_url": "https://www.education.nsw.gov.au/schooling/calendars/2026",
        "verified_at": VER,
    },
    {
        "state_code": "NSW",
        "year": 2026,
        "term_or_break_label": "Summer Break",
        "start_date": "2026-12-18",
        "end_date": "2027-01-27",
        "data_source": "NSW Department of Education",
        "source_url": "https://www.education.nsw.gov.au/schooling/calendars/2026",
        "verified_at": VER,
    },
    # NSW — https://www.education.nsw.gov.au/schooling/calendars/future-and-past-nsw-term-and-vacation-dates (2027)
    {
        "state_code": "NSW",
        "year": 2027,
        "term_or_break_label": "Term 1 Holidays",
        "start_date": "2027-04-12",
        "end_date": "2027-04-23",
        "data_source": "NSW Department of Education",
        "source_url": "https://www.education.nsw.gov.au/schooling/calendars/future-and-past-nsw-term-and-vacation-dates",
        "verified_at": VER,
    },
    {
        "state_code": "NSW",
        "year": 2027,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2027-07-05",
        "end_date": "2027-07-16",
        "data_source": "NSW Department of Education",
        "source_url": "https://www.education.nsw.gov.au/schooling/calendars/future-and-past-nsw-term-and-vacation-dates",
        "verified_at": VER,
    },
    {
        "state_code": "NSW",
        "year": 2027,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2027-09-27",
        "end_date": "2027-10-08",
        "data_source": "NSW Department of Education",
        "source_url": "https://www.education.nsw.gov.au/schooling/calendars/future-and-past-nsw-term-and-vacation-dates",
        "verified_at": VER,
    },
    {
        "state_code": "NSW",
        "year": 2027,
        "term_or_break_label": "Summer Break",
        "start_date": "2027-12-21",
        "end_date": "2028-01-28",
        "data_source": "NSW Department of Education",
        "source_url": "https://www.education.nsw.gov.au/schooling/calendars/future-and-past-nsw-term-and-vacation-dates",
        "verified_at": VER,
    },
    # VIC — https://www.vic.gov.au/school-term-dates-and-holidays-victoria (student dates; holidays = gaps)
    {
        "state_code": "VIC",
        "year": 2026,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2026-06-27",
        "end_date": "2026-07-12",
        "data_source": "Victorian Government",
        "source_url": "https://www.vic.gov.au/school-term-dates-and-holidays-victoria",
        "verified_at": VER,
    },
    {
        "state_code": "VIC",
        "year": 2026,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2026-09-19",
        "end_date": "2026-10-04",
        "data_source": "Victorian Government",
        "source_url": "https://www.vic.gov.au/school-term-dates-and-holidays-victoria",
        "verified_at": VER,
    },
    {
        "state_code": "VIC",
        "year": 2026,
        "term_or_break_label": "Summer Break",
        "start_date": "2026-12-19",
        "end_date": "2027-01-27",
        "data_source": "Victorian Government",
        "source_url": "https://www.vic.gov.au/school-term-dates-and-holidays-victoria",
        "verified_at": VER,
    },
    {
        "state_code": "VIC",
        "year": 2027,
        "term_or_break_label": "Term 1 Holidays",
        "start_date": "2027-03-26",
        "end_date": "2027-04-11",
        "data_source": "Victorian Government",
        "source_url": "https://www.vic.gov.au/school-term-dates-and-holidays-victoria",
        "verified_at": VER,
    },
    {
        "state_code": "VIC",
        "year": 2027,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2027-06-26",
        "end_date": "2027-07-11",
        "data_source": "Victorian Government",
        "source_url": "https://www.vic.gov.au/school-term-dates-and-holidays-victoria",
        "verified_at": VER,
    },
    {
        "state_code": "VIC",
        "year": 2027,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2027-09-18",
        "end_date": "2027-10-03",
        "data_source": "Victorian Government",
        "source_url": "https://www.vic.gov.au/school-term-dates-and-holidays-victoria",
        "verified_at": VER,
    },
    {
        "state_code": "VIC",
        "year": 2027,
        "term_or_break_label": "Summer Break",
        "start_date": "2027-12-18",
        "end_date": "2028-01-30",
        "data_source": "Victorian Government",
        "source_url": "https://www.vic.gov.au/school-term-dates-and-holidays-victoria",
        "verified_at": VER,
    },
    # QLD — term-dates + future-dates
    {
        "state_code": "QLD",
        "year": 2026,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2026-06-27",
        "end_date": "2026-07-12",
        "data_source": "Queensland Department of Education",
        "source_url": "https://education.qld.gov.au/about-us/calendar/term-dates",
        "verified_at": VER,
    },
    {
        "state_code": "QLD",
        "year": 2026,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2026-09-19",
        "end_date": "2026-10-05",
        "data_source": "Queensland Department of Education",
        "source_url": "https://education.qld.gov.au/about-us/calendar/term-dates",
        "verified_at": VER,
    },
    {
        "state_code": "QLD",
        "year": 2026,
        "term_or_break_label": "Summer Break",
        "start_date": "2026-12-12",
        "end_date": "2027-01-26",
        "data_source": "Queensland Department of Education",
        "source_url": "https://education.qld.gov.au/about-us/calendar/term-dates",
        "verified_at": VER,
    },
    {
        "state_code": "QLD",
        "year": 2027,
        "term_or_break_label": "Term 1 Holidays",
        "start_date": "2027-03-26",
        "end_date": "2027-04-11",
        "data_source": "Queensland Department of Education",
        "source_url": "https://education.qld.gov.au/about-us/calendar/future-dates",
        "verified_at": VER,
    },
    {
        "state_code": "QLD",
        "year": 2027,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2027-06-26",
        "end_date": "2027-07-11",
        "data_source": "Queensland Department of Education",
        "source_url": "https://education.qld.gov.au/about-us/calendar/future-dates",
        "verified_at": VER,
    },
    {
        "state_code": "QLD",
        "year": 2027,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2027-09-18",
        "end_date": "2027-10-04",
        "data_source": "Queensland Department of Education",
        "source_url": "https://education.qld.gov.au/about-us/calendar/future-dates",
        "verified_at": VER,
    },
    {
        "state_code": "QLD",
        "year": 2027,
        "term_or_break_label": "Summer Break",
        "start_date": "2027-12-11",
        "end_date": "2028-01-23",
        "data_source": "Queensland Department of Education",
        "source_url": "https://education.qld.gov.au/about-us/calendar/future-dates",
        "verified_at": VER,
    },
    # SA — https://www.education.sa.gov.au/parents-and-families/term-dates-south-australian-state-schools
    {
        "state_code": "SA",
        "year": 2026,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2026-07-04",
        "end_date": "2026-07-19",
        "data_source": "Department for Education, South Australia",
        "source_url": "https://www.education.sa.gov.au/parents-and-families/term-dates-south-australian-state-schools",
        "verified_at": VER,
    },
    {
        "state_code": "SA",
        "year": 2026,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2026-09-26",
        "end_date": "2026-10-11",
        "data_source": "Department for Education, South Australia",
        "source_url": "https://www.education.sa.gov.au/parents-and-families/term-dates-south-australian-state-schools",
        "verified_at": VER,
    },
    {
        "state_code": "SA",
        "year": 2026,
        "term_or_break_label": "Summer Break",
        "start_date": "2026-12-12",
        "end_date": "2027-01-27",
        "data_source": "Department for Education, South Australia",
        "source_url": "https://www.education.sa.gov.au/parents-and-families/term-dates-south-australian-state-schools",
        "verified_at": VER,
    },
    {
        "state_code": "SA",
        "year": 2027,
        "term_or_break_label": "Term 1 Holidays",
        "start_date": "2027-04-10",
        "end_date": "2027-04-25",
        "data_source": "Department for Education, South Australia",
        "source_url": "https://www.education.sa.gov.au/parents-and-families/term-dates-south-australian-state-schools",
        "verified_at": VER,
    },
    {
        "state_code": "SA",
        "year": 2027,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2027-07-03",
        "end_date": "2027-07-18",
        "data_source": "Department for Education, South Australia",
        "source_url": "https://www.education.sa.gov.au/parents-and-families/term-dates-south-australian-state-schools",
        "verified_at": VER,
    },
    {
        "state_code": "SA",
        "year": 2027,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2027-09-25",
        "end_date": "2027-10-10",
        "data_source": "Department for Education, South Australia",
        "source_url": "https://www.education.sa.gov.au/parents-and-families/term-dates-south-australian-state-schools",
        "verified_at": VER,
    },
    {
        "state_code": "SA",
        "year": 2027,
        "term_or_break_label": "Summer Break",
        "start_date": "2027-12-11",
        "end_date": "2028-01-26",
        "data_source": "Department for Education, South Australia",
        "source_url": "https://www.education.sa.gov.au/parents-and-families/term-dates-south-australian-state-schools",
        "verified_at": VER,
    },
    # WA — https://www.education.wa.edu.au/future-term-dates (Students tab; gazetted inclusive dates)
    {
        "state_code": "WA",
        "year": 2026,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2026-07-04",
        "end_date": "2026-07-19",
        "data_source": "School Curriculum and Standards Authority / WA Department of Education",
        "source_url": "https://www.education.wa.edu.au/future-term-dates",
        "verified_at": VER,
    },
    {
        "state_code": "WA",
        "year": 2026,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2026-09-26",
        "end_date": "2026-10-11",
        "data_source": "School Curriculum and Standards Authority / WA Department of Education",
        "source_url": "https://www.education.wa.edu.au/future-term-dates",
        "verified_at": VER,
    },
    {
        "state_code": "WA",
        "year": 2026,
        "term_or_break_label": "Summer Break",
        "start_date": "2026-12-18",
        "end_date": "2027-01-31",
        "data_source": "School Curriculum and Standards Authority / WA Department of Education",
        "source_url": "https://www.education.wa.edu.au/future-term-dates",
        "verified_at": VER,
    },
    {
        "state_code": "WA",
        "year": 2027,
        "term_or_break_label": "Term 1 Holidays",
        "start_date": "2027-04-10",
        "end_date": "2027-04-25",
        "data_source": "School Curriculum and Standards Authority / WA Department of Education",
        "source_url": "https://www.education.wa.edu.au/future-term-dates",
        "verified_at": VER,
    },
    {
        "state_code": "WA",
        "year": 2027,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2027-07-03",
        "end_date": "2027-07-18",
        "data_source": "School Curriculum and Standards Authority / WA Department of Education",
        "source_url": "https://www.education.wa.edu.au/future-term-dates",
        "verified_at": VER,
    },
    {
        "state_code": "WA",
        "year": 2027,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2027-09-25",
        "end_date": "2027-10-10",
        "data_source": "School Curriculum and Standards Authority / WA Department of Education",
        "source_url": "https://www.education.wa.edu.au/future-term-dates",
        "verified_at": VER,
    },
    {
        "state_code": "WA",
        "year": 2027,
        "term_or_break_label": "Summer Break",
        "start_date": "2027-12-18",
        "end_date": "2028-01-31",
        "data_source": "School Curriculum and Standards Authority / WA Department of Education",
        "source_url": "https://www.education.wa.edu.au/future-term-dates",
        "verified_at": VER,
    },
    # TAS — https://www.decyp.tas.gov.au/learning/term-dates/
    {
        "state_code": "TAS",
        "year": 2026,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2026-07-11",
        "end_date": "2026-07-26",
        "data_source": "Department for Education, Children and Young People (Tasmania)",
        "source_url": "https://www.decyp.tas.gov.au/learning/term-dates/",
        "verified_at": VER,
    },
    {
        "state_code": "TAS",
        "year": 2026,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2026-10-03",
        "end_date": "2026-10-18",
        "data_source": "Department for Education, Children and Young People (Tasmania)",
        "source_url": "https://www.decyp.tas.gov.au/learning/term-dates/",
        "verified_at": VER,
    },
    {
        "state_code": "TAS",
        "year": 2026,
        "term_or_break_label": "Summer Break",
        "start_date": "2026-12-19",
        "end_date": "2027-02-03",
        "data_source": "Department for Education, Children and Young People (Tasmania)",
        "source_url": "https://www.decyp.tas.gov.au/learning/term-dates/",
        "verified_at": VER,
    },
    {
        "state_code": "TAS",
        "year": 2027,
        "term_or_break_label": "Term 1 Holidays",
        "start_date": "2027-04-10",
        "end_date": "2027-04-25",
        "data_source": "Department for Education, Children and Young People (Tasmania)",
        "source_url": "https://www.decyp.tas.gov.au/learning/term-dates/",
        "verified_at": VER,
    },
    {
        "state_code": "TAS",
        "year": 2027,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2027-07-03",
        "end_date": "2027-07-18",
        "data_source": "Department for Education, Children and Young People (Tasmania)",
        "source_url": "https://www.decyp.tas.gov.au/learning/term-dates/",
        "verified_at": VER,
    },
    {
        "state_code": "TAS",
        "year": 2027,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2027-09-25",
        "end_date": "2027-10-10",
        "data_source": "Department for Education, Children and Young People (Tasmania)",
        "source_url": "https://www.decyp.tas.gov.au/learning/term-dates/",
        "verified_at": VER,
    },
    # NT — https://nt.gov.au/learning/primary-and-secondary-students/school-term-dates-in-nt (student dates; gaps)
    {
        "state_code": "NT",
        "year": 2026,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2026-06-20",
        "end_date": "2026-07-13",
        "data_source": "Northern Territory Government",
        "source_url": "https://nt.gov.au/learning/primary-and-secondary-students/school-term-dates-in-nt",
        "verified_at": VER,
    },
    {
        "state_code": "NT",
        "year": 2026,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2026-09-19",
        "end_date": "2026-10-05",
        "data_source": "Northern Territory Government",
        "source_url": "https://nt.gov.au/learning/primary-and-secondary-students/school-term-dates-in-nt",
        "verified_at": VER,
    },
    {
        "state_code": "NT",
        "year": 2026,
        "term_or_break_label": "Summer Break",
        "start_date": "2026-12-11",
        "end_date": "2027-01-26",
        "data_source": "Northern Territory Government",
        "source_url": "https://nt.gov.au/learning/primary-and-secondary-students/school-term-dates-in-nt",
        "verified_at": VER,
    },
    {
        "state_code": "NT",
        "year": 2027,
        "term_or_break_label": "Term 1 Holidays",
        "start_date": "2027-04-03",
        "end_date": "2027-04-12",
        "data_source": "Northern Territory Government",
        "source_url": "https://nt.gov.au/learning/primary-and-secondary-students/school-term-dates-in-nt",
        "verified_at": VER,
    },
    {
        "state_code": "NT",
        "year": 2027,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2027-06-19",
        "end_date": "2027-07-12",
        "data_source": "Northern Territory Government",
        "source_url": "https://nt.gov.au/learning/primary-and-secondary-students/school-term-dates-in-nt",
        "verified_at": VER,
    },
    {
        "state_code": "NT",
        "year": 2027,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2027-09-18",
        "end_date": "2027-10-04",
        "data_source": "Northern Territory Government",
        "source_url": "https://nt.gov.au/learning/primary-and-secondary-students/school-term-dates-in-nt",
        "verified_at": VER,
    },
    {
        "state_code": "NT",
        "year": 2027,
        "term_or_break_label": "Summer Break",
        "start_date": "2027-12-10",
        "end_date": "2028-01-24",
        "data_source": "Northern Territory Government",
        "source_url": "https://nt.gov.au/learning/primary-and-secondary-students/school-term-dates-in-nt",
        "verified_at": VER,
    },
    # ACT — https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-saving (continuing students)
    {
        "state_code": "ACT",
        "year": 2026,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2026-07-04",
        "end_date": "2026-07-20",
        "data_source": "ACT Government",
        "source_url": "https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-saving",
        "verified_at": VER,
    },
    {
        "state_code": "ACT",
        "year": 2026,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2026-09-26",
        "end_date": "2026-10-12",
        "data_source": "ACT Government",
        "source_url": "https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-saving",
        "verified_at": VER,
    },
    {
        "state_code": "ACT",
        "year": 2026,
        "term_or_break_label": "Summer Break",
        "start_date": "2026-12-19",
        "end_date": "2027-02-01",
        "data_source": "ACT Government",
        "source_url": "https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-saving",
        "verified_at": VER,
    },
    {
        "state_code": "ACT",
        "year": 2027,
        "term_or_break_label": "Term 1 Holidays",
        "start_date": "2027-04-10",
        "end_date": "2027-04-27",
        "data_source": "ACT Government",
        "source_url": "https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-saving",
        "verified_at": VER,
    },
    {
        "state_code": "ACT",
        "year": 2027,
        "term_or_break_label": "Term 2 Holidays",
        "start_date": "2027-07-03",
        "end_date": "2027-07-19",
        "data_source": "ACT Government",
        "source_url": "https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-saving",
        "verified_at": VER,
    },
    {
        "state_code": "ACT",
        "year": 2027,
        "term_or_break_label": "Term 3 Holidays",
        "start_date": "2027-09-25",
        "end_date": "2027-10-11",
        "data_source": "ACT Government",
        "source_url": "https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-saving",
        "verified_at": VER,
    },
    {
        "state_code": "ACT",
        "year": 2027,
        "term_or_break_label": "Summer Break",
        "start_date": "2027-12-18",
        "end_date": "2028-02-01",
        "data_source": "ACT Government",
        "source_url": "https://www.act.gov.au/living-in-the-act/public-holidays-school-terms-and-daylight-saving",
        "verified_at": VER,
    },
]

# --- Public holidays: Fair Work 2026 list from 2026-public-holidays (observed >= 2026-04-27) ---

FW = "https://www.fairwork.gov.au/employment-conditions/public-holidays/2026-public-holidays"

PUBLIC: list[dict] = [
    # Representative rows per jurisdiction from Fair Work 2026 page (state-specific lists).
    {"state_code": "NSW", "year": 2026, "holiday_name": "Anzac Day — additional public holiday", "observed_date": "2026-04-27", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
    {"state_code": "NSW", "year": 2026, "holiday_name": "King's Birthday", "observed_date": "2026-06-08", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
    {"state_code": "NSW", "year": 2026, "holiday_name": "Labour Day", "observed_date": "2026-10-05", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
    {"state_code": "NSW", "year": 2026, "holiday_name": "Christmas Day", "observed_date": "2026-12-25", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
    {"state_code": "NSW", "year": 2026, "holiday_name": "Boxing Day", "observed_date": "2026-12-26", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
    {"state_code": "NSW", "year": 2026, "holiday_name": "Additional public holiday for Boxing Day", "observed_date": "2026-12-28", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
    {"state_code": "VIC", "year": 2026, "holiday_name": "Melbourne Cup", "observed_date": "2026-11-03", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
    {"state_code": "VIC", "year": 2026, "holiday_name": "King's Birthday", "observed_date": "2026-06-08", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
    {"state_code": "QLD", "year": 2026, "holiday_name": "King's Birthday", "observed_date": "2026-10-05", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
    {"state_code": "QLD", "year": 2026, "holiday_name": "Royal Queensland Show (Brisbane area only)", "observed_date": "2026-08-12", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
    {"state_code": "WA", "year": 2026, "holiday_name": "King's Birthday", "observed_date": "2026-09-28", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
    {"state_code": "SA", "year": 2026, "holiday_name": "King's Birthday", "observed_date": "2026-06-08", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
    {"state_code": "TAS", "year": 2026, "holiday_name": "Recreation Day", "observed_date": "2026-11-02", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
    {"state_code": "ACT", "year": 2026, "holiday_name": "Reconciliation Day", "observed_date": "2026-06-01", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
    {"state_code": "NT", "year": 2026, "holiday_name": "Picnic Day", "observed_date": "2026-08-03", "is_national": False, "data_source": "Fair Work Ombudsman", "source_url": FW, "verified_at": VER},
]

# Remove ACT Canberra Day — Mar 9 < Apr 27
PUBLIC = [r for r in PUBLIC if r["observed_date"] >= TODAY]

EVENTS: list[dict] = [
    {
        "event_slug": "vivid-sydney-2026",
        "event_name": "Vivid Sydney",
        "event_type": "festival",
        "state_code": "NSW",
        "lga_or_area": "City of Sydney",
        "event_lat": -33.861,
        "event_lng": 151.211,
        "start_date": "2026-05-22",
        "end_date": "2026-06-13",
        "is_recurring_annual": True,
        "expected_visitors_label": "millions",
        "notes": "Light festival across Sydney CBD and harbour precincts.",
        "data_source": "Destination NSW (event operator site)",
        "source_url": "https://www.vividsydney.com/",
        "verified_at": VER,
    },
    {
        "event_slug": "australian-open-2027",
        "event_name": "Australian Open",
        "event_type": "sport",
        "state_code": "VIC",
        "lga_or_area": "Melbourne Park",
        "event_lat": -37.822,
        "event_lng": 144.978,
        "start_date": "2027-01-11",
        "end_date": "2027-01-31",
        "is_recurring_annual": True,
        "expected_visitors_label": "hundreds_of_thousands",
        "notes": "Grand Slam tennis; 2027 dates per Tennis Australia announcement.",
        "data_source": "Tennis Australia",
        "source_url": "https://ausopen.com/articles/news/australian-open-2027-dates-announced",
        "verified_at": VER,
    },
    {
        "event_slug": "melbourne-cup-day-2026",
        "event_name": "Melbourne Cup Day",
        "event_type": "sport",
        "state_code": "VIC",
        "lga_or_area": "City of Melbourne",
        "event_lat": -37.787,
        "event_lng": 144.907,
        "start_date": "2026-11-03",
        "end_date": "2026-11-03",
        "is_recurring_annual": True,
        "expected_visitors_label": "tens_of_thousands",
        "notes": "Public holiday race day; metropolitan Melbourne.",
        "data_source": "Fair Work Ombudsman (public holiday listing)",
        "source_url": FW,
        "verified_at": VER,
    },
]


def main() -> None:
    for path, data in (
        (ROOT / "data" / "seed_school_holidays_AU.json", SCHOOL),
        (ROOT / "data" / "seed_public_holidays_AU.json", PUBLIC),
        (ROOT / "data" / "seed_major_events_AU.json", EVENTS),
    ):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
        print("wrote", path, "rows", len(data))


if __name__ == "__main__":
    main()
